#eureka client配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance: 
    # 注册时使用ip而不是主机名
    preferIpAddress: true
    instanceId: ${server.ipAddress}:${server.port}
    health-check-url-path: /actuator/health
    # 状态地址为api地址
    statusPageUrlPath: /${server.servlet.contextpath:}/apidoc.html


server: 
  ipAddress: 127.0.0.1
  port: 19721
  servlet: 
    contextpath: 

pool:
  initialSize: 10

transaction:
  rollback-on-commit-failure: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #InnoDB才能支持事务
  application:
    name: service-eis
  devtools: 
    restart: 
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qunchuang
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #初始化大小
    initialSize: ${pool.initialSize}
    #最小空閒
    minIdle: 5
    #最大連接數
    maxActive: 50
    #最大等待時間
    maxWait: 60000
    #最小生存時間
    minEvictableIdleTimeMillis: 25200000
  datasource2:
    wmsDatasourceType: release/beta
    url: jdbc:oracle:thin:@10.189.128.237:1521:thaws
    username: ASRS_ITR1
    password: ASRS_ITR1
    driverClassName: oracle.jdbc.OracleDriver
    #初始化大小
    initialSize: ${pool.initialSize}
    #最小空閒
    minIdle: 5
    #最大連接數
    maxActive: 50
    #最大等待時間
    maxWait: 60000
    #最小生存時間
    minEvictableIdleTimeMillis: 25200000
prolog:
  apidoc: #api文档配置文件
    title: 用户服务
    basePackage: com.prolog.eis
    description: 用户服务
    version: 1.0
  dao: 
    dialect: mysql
    pagehelper: #pagehelper分页插件配置
      helperDialect: ${prolog.dao.dialect}
      reasonable: true
      supportMethodsArguments: true
      pageSizeZero: false
      params: count=countSql
    #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
    mybatis:
      typeAliasesPackage: com.prolog.eis.model
      mapperLocations: classpath:mappers/*.xml
      mapUnderscoreToCamelCase: true
      
  web: 
    multipart:  #文件上传配置
      maxFileSize: 100MB
      maxRequestSize: 100MB
      


  
      
  